services:
  node0:
    container_name: crdt_node0
    build: .
    command: ["-id=0", "-address=node0:8090", "-peers=node0:8090,node1:8091,node2:8092"]
    ports:
      - "8090:8090"
    networks:
      crdt-network:
        ipv4_address: 172.16.240.10

  node1:
    container_name: crdt_node1
    build: .
    command: ["-id=1", "-address=node1:8091", "-peers=node0:8090,node1:8091,node2:8092"]
    ports:
      - "8091:8091"
    networks:
      crdt-network:
        ipv4_address: 172.16.240.11

  node2:
    container_name: crdt_node2
    build: .
    command: ["-id=2", "-address=node2:8092", "-peers=node0:8090,node1:8091,node2:8092"]
    ports:
      - "8092:8092"
    networks:
      crdt-network:
        ipv4_address: 172.16.240.12

networks:
  crdt-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.240.0/24
